export const addProductFormDefaultValues = {
  expiry: new Date(),
  tags: [] as any[],
  attributes: [] as any[],
  name: "",
  category: [] as any[],
  subCategory: [] as any[],
  productType: "",
  intendedUse: "",
  sku: "",
  gtin: "",
  hsn: "",
  unspsc: "",
  upsells: "",
  crosssells: "",
  manufacturerName: "",
  email: "",
  phone: "",
  origin: "",
  shortdescription: "",
  description: "",
  productWgt: "",
  productWgtUnit: "",
  dimensionUnit: "",
  dimension_h: "",
  dimension_l: "",
  dimension_w: "",
  // colorOptions: "",
  sterileString: "",
  singleUseString: "",
  productCompilance: null as any,
  msds_ifu_leaflet: null as any,
  // originalPrice: "",
  // discountPrice: "",
  // institutePrice: "",
  minmaxrule: { maxQty: "", minQty: "" },
  taxClass: "",
  taxStatus: "",
  // stocks: "",
  unitOfMeasure: "",
  stockStatus: "",
  deliveryLeadTime: "",
  warranty: "",
  amc_cms: null as any,
  rma: "",
  dispatchLocation: "",
  dispatchPinCode: "",
  unitsPerCarton: "",
  shippingWeight: "",
  packagingType: "",
  // deliveryPartner: "",
  deliveryInstruction: "",
  shelfing_storage_req: "",
  purchaseNote: "",
  certificate: [] as any[],
  oemLetter: null as any,
  productComparisionSheet: null as any,
  specialityPackage: "",
  specialityPackageType: "",
  variants: [{
    size: null as string | null,
    colorOption: null as string | null,
    originalPrice: "",
    discountPrice: "",
    stocks: ""
  }]
}

export type FormProduct = typeof addProductFormDefaultValues
