export const addProductFormDefaultValues = {
  expiry: new Date(),
  tags: [] as any[],
  attributes: [] as any[],
  name: "",
  brand: "",
  category: [] as any[],
  subCategory: [] as any[],
  productType: undefined as string | undefined,
  intendedUse: undefined as string | undefined,
  sku: "",
  gtin: "",
  hsn: "",
  unspsc: "",
  upsells: [] as string[],
  crosssells: [] as string[],
  manufacturerName: "",
  email: "",
  phone: "",
  origin: "",
  shortdescription: "",
  description: "",
  productWgt: "",
  productWgtUnit: undefined as string | undefined,
  dimensionUnit: undefined as string | undefined,
  dimension_h: "",
  dimension_l: "",
  dimension_w: "",
  // colorOptions: "",
  sterileString: "",
  singleUseString: "",
  productCompilance: null as any,
  msds_ifu_leaflet: null as any,
  // originalPrice: "",
  // discountPrice: "",
  // institutePrice: "",
  minmaxrule: { maxQty: "", minQty: "" },
  taxClass: undefined as string | undefined,
  taxStatus: undefined as string | undefined,
  // stocks: "",
  unitOfMeasure: "",
  stockStatus: "",
  deliveryLeadTime: "",
  warranty: "",
  amc_cms: null as any,
  rma: "",
  dispatchLocation: "",
  dispatchPinCode: "",
  unitsPerCarton: "",
  shippingWeight: "",
  packagingType: "",
  // deliveryPartner: "",
  deliveryInstruction: "",
  shelfing_storage_req: "",
  purchaseNote: "",
  certificate: [] as any[],
  oemLetter: null as any,
  productComparisionSheet: null as any,
  specialityPackage: "",
  specialityPackageType: "",
  variants: [
    {
      size: null as string | null,
      colorOption: null as string | null,
      originalPrice: "",
      discountPrice: "",
      stocks: "",
      bulkOrders: [] as {
        qty?: number | undefined;
        price?: number | undefined;
      }[],
    },
  ],
  dispatchState: "",
  dispatchDistrict: "",
};

export type FormProduct = typeof addProductFormDefaultValues;
