 export const API_URL = "http://localhost:8000/api/v2/";
 // export const API_URL = "https://www.semamart.com/api/v2/"
export const BASE_URL = "http://localhost:8000/"
  // export const BASE_URL = "https://www.semamart.com/"
//export const BASE_URL = "http://localhost:8000/";
 //export const API_URL = "https://test.semamart.com/api/v2/"
  //export const BASE_URL = "https://test.semamart.com/"
//  export const API_URL = "https://www.semamart.com/api/v2/"
 // export const API_URL = "https://test.semamart.com/api/v2/"
  //export const BASE_URL = "https://test.semamart.com/"
